-- liquibase formatted sql

-- changeset codex:automation-ui-scene-base-20260729
-- comment 初始化 UI 自动化场景主表，必须在场景字段增量迁移前执行
CREATE TABLE IF NOT EXISTS `automation_ui_scene` (
    `id`             bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `scene_id`       varchar(64) NOT NULL COMMENT '场景业务 ID',
    `name`           varchar(64) NOT NULL COMMENT '场景名称',
    `description`    varchar(255) DEFAULT NULL COMMENT '场景描述',
    `project_id`     bigint NOT NULL COMMENT '所属项目 ID',
    `project_name`   varchar(64) DEFAULT NULL COMMENT '所属项目名称',
    `version_id`     bigint NOT NULL COMMENT '所属项目版本 ID',
    `version_name`   varchar(64) DEFAULT NULL COMMENT '所属项目版本名称',
    `module_id`      bigint NOT NULL COMMENT '所属模块 ID',
    `module_path`    varchar(255) DEFAULT NULL COMMENT '所属模块路径',
    `level`          varchar(64) DEFAULT NULL COMMENT '场景等级',
    `status`         tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT '场景状态',
    `tags`           json DEFAULT NULL COMMENT '场景标签',
    `case_list`      json DEFAULT NULL COMMENT '场景用例定义',
    `test_plan_id`   json DEFAULT NULL COMMENT '关联的测试计划 ID 列表',
    `report_id`      bigint DEFAULT NULL COMMENT '所属测试报告 ID',
    `debug_record`   json DEFAULT NULL COMMENT '调试记录',
    `execute_status` varchar(64) DEFAULT NULL COMMENT '执行状态',
    `execute_result` varchar(64) DEFAULT NULL COMMENT '执行结果',
    `test_record`    json DEFAULT NULL COMMENT '测试记录',
    `build_number`   int DEFAULT NULL COMMENT 'Jenkins 构建编号',
    `console_url`    varchar(500) DEFAULT NULL COMMENT 'Jenkins 控制台日志地址',
    `test_report_url` varchar(500) DEFAULT NULL COMMENT 'Jenkins 测试报告地址',
    `case_total`     int DEFAULT NULL COMMENT '场景用例总数',
    `case_pass`      int DEFAULT NULL COMMENT '场景用例通过数',
    `case_fail`      int DEFAULT NULL COMMENT '场景用例失败数',
    `case_skip`      int DEFAULT NULL COMMENT '场景用例跳过数',
    `pass_rate`      varchar(32) DEFAULT NULL COMMENT '场景用例通过率',
    `last_result`    varchar(64) DEFAULT NULL COMMENT '最后执行结果',
    `step_total`     int DEFAULT NULL COMMENT '场景用例步骤总数',
    `step_pass`      int DEFAULT NULL COMMENT '场景用例步骤成功数',
    `step_fail`      int DEFAULT NULL COMMENT '场景用例步骤失败数',
    `step_skip`      int DEFAULT NULL COMMENT '场景用例步骤跳过数',
    `create_user`    bigint DEFAULT NULL COMMENT '创建人',
    `create_time`    datetime DEFAULT NULL COMMENT '创建时间',
    `update_user`    bigint DEFAULT NULL COMMENT '修改人',
    `update_time`    datetime DEFAULT NULL COMMENT '修改时间',
    `update_ip`      varchar(255) DEFAULT NULL COMMENT '修改人 IP',
    `del_flag`       tinyint NOT NULL DEFAULT 3 COMMENT '删除标志：3 正常，4 异常',
    PRIMARY KEY (`id`),
    INDEX `idx_automation_ui_scene_identity` (`project_id`, `version_id`, `scene_id`, `del_flag`),
    INDEX `idx_automation_ui_scene_scene_id` (`scene_id`),
    INDEX `idx_automation_ui_scene_module_id` (`module_id`),
    INDEX `idx_automation_ui_scene_status` (`status`),
    INDEX `idx_automation_ui_scene_execute_status` (`execute_status`),
    INDEX `idx_automation_ui_scene_create_user` (`create_user`),
    INDEX `idx_automation_ui_scene_update_user` (`update_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='UI 自动化场景表';

-- definition_version 由后续 changeset 新增，避免新库初始化时重复加列。
